soft/user_interface/autolights/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('user_interface.config.urls')),

]

soft/user_interface/config/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^list-config$', views.list_config, name='list-config'),
    url(r'^config/([0-9]+)$', views.edit_config, name='edit-config'),
    url(r'^add-config$', views.add_config, name='add-config'),
    url(r'^config/([0-9]+)/del$', views.del_config, name='del-config'),
    url(r'^config/([0-9]+)/active$', views.active_config, name='active-config'),
    url(r'^continuous-rule/([0-9]+)$', views.edit_continuous_rule, name='edit-continuous-rule'),
    url(r'^standard-rule/([0-9]+)$', views.edit_standard_rule, name='edit-standard-rule'),
    url(r'^bank-rule/([0-9]+)$', views.edit_bank_rule, name='edit-bank-rule'),
    url(r'^chase-rule/([0-9]+)$', views.edit_chase_rule, name='edit-chase-rule'),
    url(r'^config/([0-9]+)/add-continuous-rule$', views.add_continuous_rule, name='add-continuous-rule'),
    url(r'^config/([0-9]+)/add-standard-rule$', views.add_standard_rule, name='add-standard-rule'),
    url(r'^config/([0-9]+)/add-bank-rule$', views.add_bank_rule, name='add-bank-rule'),
    url(r'^config/([0-9]+)/add-chase-rule$', views.add_chase_rule, name='add-chase-rule'),
    url(r'^continuous-rule/([0-9]+)/del$', views.del_continuous_rule, name='del-continuous-rule'),
    url(r'^standard-rule/([0-9]+)/del$', views.del_standard_rule, name='del-standard-rule'),
    url(r'^bank-rule/([0-9]+)/del$', views.del_bank_rule, name='del-bank-rule'),
    url(r'^chase-rule/([0-9]+)/del$', views.del_chase_rule, name='del-chase-rule'),
    url(r'^bank-rule/([0-9]+)/add-state$', views.add_bank_rule_state, name='add-bank-rule-state'),
    url(r'^chase-rule/([0-9]+)/add-state$', views.add_chase_rule_state, name='add-chase-rule-state'),
    url(r'^bank-rule-state/([0-9]+)$', views.edit_bank_rule_state, name='edit-bank-rule-state'),
    url(r'^chase-rule-state/([0-9]+)$', views.edit_chase_rule_state, name='edit-chase-rule-state'),
    url(r'^bank-rule-state/([0-9]+)/del$', views.del_bank_rule_state, name='del-bank-rule-state'),
    url(r'^chase-rule-state/([0-9]+)/del$', views.del_chase_rule_state, name='del-chase-rule-state'),
    url(r'^standard-rule/condition/([0-9]+)/del$', views.del_standard_rule_condition, name='del-standard-rule-condition'),
    url(r'^chase-rule/condition/([0-9]+)/del$', views.del_chase_rule_condition, name='del-chase-rule-condition'),
    url(r'^bank-rule-state/condition/([0-9]+)/del$', views.del_bank_rule_state_condition, name='del-bank-rule-state-condition'),
    url(r'^chase-rule/([0-9]+)/condition/add', views.add_chase_rule_condition, name='add-chase-rule-condition'),
    url(r'^bank-rule-state/([0-9]+)/condition/add', views.add_bank_rule_state_condition, name='add-bank-rule-state-condition'),
    url(r'^standard-rule/([0-9]+)/condition/add', views.add_standard_rule_condition, name='add-standard-rule-condition'),
    url(r'^chase-rule/condition/([0-9]+)', views.edit_chase_rule_condition, name='edit-chase-rule-condition'),
    url(r'^bank-rule-state/condition/([0-9]+)', views.edit_bank_rule_state_condition, name='edit-bank-rule-state-condition'),
    url(r'^standard-rule/condition/([0-9]+)', views.edit_standard_rule_condition, name='edit-standard-rule-condition'),
]

soft/user_interface/config/models.py
from django.db import models
from . import parameters as params


# Configuration
#   - ContinuousRule
#   - StandardRule
#       - StandardRuleCondition
#   - BankRule
#       - BankRuleState
#           - BankRuleStateCondition
#   - ChaseRule
#       - ChaseRuleState


# LedWall config model
class Configuration(models.Model):
    name = models.CharField(max_length=100, null=True)  # Configuration's name
    description = models.TextField(null=True)           # If necessary, add a description
    creation = models.DateTimeField(auto_now_add=True, auto_now=False,
                                verbose_name="Creation")
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.active:
            try:
                temp = Configuration.objects.get(active=True)
                if self != temp:
                    temp.active = False
                    temp.save()
            except Configuration.DoesNotExist:
                pass
        super(Configuration, self).save(*args, **kwargs)


# Rules

class Rule(models.Model):
    name = models.CharField(max_length=100)             # Rule's name
    config = models.ForeignKey('Configuration', on_delete=models.CASCADE)         # Configuration the rule belong to

    class Meta:
        abstract = True


class ContinuousRule(Rule):
    midi_cc = models.IntegerField()                     # Midi control to link
    continuous_param = models.IntegerField(choices=params.CONTINUOUS_PARAM, default=params.BPM_CONTINUOUS)    # Param to link
    scale_down = models.IntegerField()                  # Setting full scale
    scale_up = models.IntegerField()

    def __str__(self):
        return self.name


class StandardRule(Rule):
    note = models.IntegerField()                        # Midi note
    event_param = models.IntegerField(choices=params.EVENTS_PARAM, default=params.BEAT_EVENT)    # Param to link
    max_duration = models.IntegerField(default=0)       # Note duration in ms, 0 --> infinite

    def __str__(self):
        return self.name


class BankRule(Rule):
    max_duration = models.IntegerField(null=True)       # Max duration of a state

    def __str__(self):
        return self.name


class ChaseRule(Rule):
    event_param = models.IntegerField(choices=params.EVENTS_PARAM, default=params.BEAT_EVENT)    # Param to link
    state_duration = models.IntegerField()              # Duration of a state
    random_states = models.BooleanField()               # Set state order to random

    def __str__(self):
        return self.name


# Conditions

class Condition(models.Model):
    # Boolean condition
    bool_param = models.IntegerField(choices=params.BOOLEAN_PARAM, null=True, blank=True)    # Param to link
    bool_active_on_false = models.BooleanField(default=False)
    # Continuous condition
    continuous_param = models.IntegerField(choices=params.CONTINUOUS_PARAM, null=True, blank=True, default=params.BPM_CONTINUOUS)
    operator = models.CharField(
        max_length=3,
        choices=(('<', '<'),('=', '='),('>', '>')),
        default='<')
    value = models.IntegerField(null=True, blank=True)                                      # Value to compare with

    class Meta:
        abstract = True

    def __str__(self):
        if self.bool_param:
            disp = self.get_bool_param_display()
            if self.bool_active_on_false:
                disp = "not " + disp
            return disp
        else: return str(self.get_continuous_param_display()) + self.operator + str(self.value)


class StandardRuleCondition(Condition):
    rule = models.ForeignKey('StandardRule', on_delete=models.CASCADE)            # Rule's the condition belongs to


class BankRuleStateCondition(Condition):
    state = models.ForeignKey('BankRuleState', on_delete=models.CASCADE)           # State's the condition belongs to


class ChaseRuleCondition(Condition):
    rule = models.ForeignKey('ChaseRule', on_delete=models.CASCADE)               # State's the condition belongs to


# States

class State(models.Model):
    name = models.CharField(max_length=100)  # State name
    note = models.IntegerField()  # Midi note

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class BankRuleState(State):
    rule = models.ForeignKey('BankRule', on_delete=models.CASCADE)                # Rule this action belongs to
    priority = models.IntegerField()                    # Priority between 1 to 100


class ChaseRuleState(State):
    rule = models.ForeignKey('ChaseRule', on_delete=models.CASCADE)               # Rule this action belongs to

soft/user_interface/config/forms.py
from django import forms
from .models import *


class ConfigurationForm(forms.ModelForm):
    class Meta:
        model = Configuration
        fields = ['name', 'description']


class ContinuousRuleForm(forms.ModelForm):
    class Meta:
        model = ContinuousRule
        fields = ['name', 'midi_cc', 'continuous_param', 'scale_down', 'scale_up']


class StandardRuleForm(forms.ModelForm):
    class Meta:
        model = StandardRule
        fields = ['name', 'note', 'event_param', 'max_duration']


class BankRuleForm(forms.ModelForm):
    class Meta:
        model = BankRule
        fields = ['name', 'max_duration']


class ChaseRuleForm(forms.ModelForm):
    class Meta:
        model = ChaseRule
        fields = ['name', 'event_param', 'state_duration', 'random_states']


class BankRuleStateForm(forms.ModelForm):
    class Meta:
        model = BankRuleState
        fields = ['name', 'note', 'priority']


class ChaseRuleStateForm(forms.ModelForm):
    class Meta:
        model = ChaseRuleState
        fields = ['name', 'note']


class ConditionForm(forms.ModelForm):
    class Meta:
        model = Condition
        fields = ['bool_param', 'bool_active_on_false', 'continuous_param', 'operator', 'value']

soft/user_interface/config/templates/config/condition.html
{% extends "base.html" %}
{% load static %}
{% block title %}Edit conditions{% endblock %}
{% block where_am_i %}
<li><a href="{% url 'edit-config' config.id %}">{{ config.name }}</a></li>
<li> > </li>
{% if bank_rule_state %}
<li><a href="{% url 'edit-bank-rule' bank_rule_state.rule.id %}">{{ bank_rule_state.rule.name }}</a></li>
<li> > </li>
<li><a href="{% url 'edit-bank-rule-state' bank_rule_state.id %}">{{ bank_rule_state.name }}</a></li>
{% endif %}
{% if standard %}
<li><a href="{% url 'edit-standard-rule' standard.id %}">{{ standard.name }}</a></li>
{% endif %}
{% if chase %}
<li><a href="{% url 'edit-chase-rule' chase.id %}">{{ chase.name }}</a></li>
{% endif %}
<li><a href="{% url 'edit-bank-rule' rule.id %}">{{ rule.name }}</a></li>
{% endif %}
<li> > </li>
<li>Edit conditions</li>
{% endblock %}
{% block content %}
        <div class="flex">
            <div class="block">
                <h2>Conditions</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Condition</th>
                            <th></th>
                        </tr>
                    </thead>
                    {% for cond in conditions %}
                        <tr>
                            <td>{{ cond }}</td>
                            <td class="last">
                                <a class="round-button" href="{% url 'edit-condition' cond.id %}">Edit</a>
                                <a class="round-button" href="{% url 'del-condition' cond.id %}">Delete</a>
                            </td>
                        </tr>
                    {% empty %}
                        <p>No condition</p>
                    {% endfor %}
                </table>
            </div>
            <div class="block">
                {% if add %}
                <h2>Add condition</h2>
                    {% if bank_rule_state %}
                        <form action="{% url 'add-bank-rule-state-condition' bank_rule_state.id %}" method="post">
                    {% endif %}
                    {% if standard %}
                        <form action="{% url 'add-bank-rule-state-condition' standard.id %}" method="post">
                    {% endif %}
                    {% if chase %}
                        <form action="{% url 'add-bank-rule-state-condition' chase.id %}" method="post">
                    {% endif %}
                {% else %}
                <h2>Edit condition</h2>
                <form action="{% url 'edit-condition' condition.id %}" method="post">
                {% endif %}
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
                </form>
            </div>
        </div>
{% endblock %}

soft/user_interface/config/templates/config/edit-bank-rule.html
{% extends "base.html" %}
{% load static %}
{% block title %}Edit a bank rule{% endblock %}
{% block where_am_i %}
<li><a href="{% url 'edit-config' config.id %}">{{ config.name }}</a></li>
<li> > </li>
<li> Bank rule </li>
<li> > </li>
{% if add %}
<li>New bank rule</li>
{% else %}
<li><a href="{% url 'edit-bank-rule' rule.id %}">{{ rule.name }}</a></li>
{% endif %}
{% endblock %}
{% block content %}
        <div class="flex">
            <div class="block">
                <h2>Bank rule infos</h2>
                {% if add %}
                <form action="{% url 'add-bank-rule' config.id %}" method="post">
                {% else %}
                <form action="{% url 'edit-bank-rule' rule.id %}" method="post">
                {% endif %}
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
                </form>
            </div>
            <div class="block">
                <h2>States</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Note</th>
                            <th>Priority</th>
                            <th>Conditions</th>
                            <th></th>
                        </tr>
                    </thead>
                    {% for state in rule.bankrulestate_set.all %}
                        <tr>
                            <td>{{ state.name }}</td>
                            <td>#{{ state.note }}</td>
                            <td>{{ state.priority }}</td>
                            <td>
                                {% for condition in state.bankrulestatecondition_set.all %}
                                {{ condition }} <br />
                                {% endfor %}
                            </td>
                            <td class="last">
                                <a class="round-button" href="{% url 'edit-bank-rule-state' state.id %}">Edit</a>
                                <a class="round-button" href="{% url 'del-bank-rule-state' state.id %}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
                <h2>Conditions</h2>
                <table>
                    <thead>
                        <tr>
                            <th>States</th>
                            <th>Conditions</th>
                            <th></th>
                        </tr>
                    </thead>
                        {% for state in rule.bankrulestate_set.all %}
                            <tr><td>{{ state.name }}</td>
                                <td></td>
                                <td class="last"><a class="round-button" href="{% url 'add-bank-rule-state-condition' state.id %}">Add</a></td>
                            </tr>
                            {% for cond in state.bankrulestatecondition_set.all %}
                                <tr>
                                    <td></td>
                                    <td>{{ cond }} </td>
                                    <td class="last">
                                        <a class="round-button" href="{% url 'edit-bank-rule-state-condition' cond.id %}">Edit</a>
                                        <a class="round-button" href="{% url 'del-bank-rule-state-condition' cond.id %}">Delete</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endfor %}
                </table>
            </div>
            <div class="block">
                {% if not condition_form %}
                    {% if add_state %}
                    <h2>Add state</h2>
                    <form action="{% url 'add-bank-rule-state' rule.id %}" method="post">
                    {% else %}
                    <h2>Edit state</h2>
                    <form action="{% url 'edit-bank-rule-state' state.id %}" method="post">
                    {% endif %}
                    {% csrf_token %}
                    {{ form_state.as_p }}
                    <input type="submit" value="Save" />
                    </form>
                {% endif %}
                {% if condition_form %}
                    {% if add_cond %}
                    <h2>Add condition</h2>
                    <form action="{% url 'add-bank-rule-state-condition' state.id %}" method="post">
                    {% else %}
                    <h2>Edit condition</h2>
                    <form action="{% url 'edit-bank-rule-state-condition' condition.id %}" method="post">
                    {% endif %}
                    {% csrf_token %}
                    {{ form_cond.as_p }}
                    <input type="submit" value="Save" />
                    </form>
                {% endif %}
            </div>
        </div>
{% endblock %}

soft/user_interface/config/templates/config/edit-chase-rule.html
{% extends "base.html" %}
{% load static %}
{% block title %}Edit a bank rule{% endblock %}
{% block where_am_i %}
<li><a href="{% url 'edit-config' config.id %}">{{ config.name }}</a></li>
<li> > </li>
<li> Chase rule </li>
<li> > </li>
{% if add %}
<li>New chase rule</li>
{% else %}
<li><a href="{% url 'edit-chase-rule' rule.id %}">{{ rule.name }}</a></li>
{% endif %}
{% endblock %}
{% block content %}
        <div class="flex">
            <div class="block">
                <h2>Chase rule infos</h2>
                {% if add %}
                <form action="{% url 'add-chase-rule' config.id %}" method="post">
                {% else %}
                <form action="{% url 'edit-chase-rule' rule.id %}" method="post">
                {% endif %}
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
                </form>
            </div>
            <div class="block">
                <h2>States</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Note</th>
                            <th></th>
                        </tr>
                    </thead>
                    {% for state in rule.chaserulestate_set.all %}
                        <tr>
                            <td>{{ state.name }}</td>
                            <td>#{{ state.note }}</td>
                            <td class="last">
                                <a class="round-button" href="{% url 'edit-chase-rule-state' state.id %}">Edit</a>
                                <a class="round-button" href="{% url 'del-chase-rule-state' state.id %}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
                <h2>Conditions</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Conditions</th>
                            <th></th>
                        </tr>
                    </thead>
                    {% for cond in rule.chaserulecondition_set.all %}
                        <tr>
                            <td>{{ cond }} </td>
                            <td class="last">
                                <a class="round-button" href="{% url 'edit-chase-rule-condition' cond.id %}">Edit</a>
                                <a class="round-button" href="{% url 'del-chase-rule-condition' cond.id %}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="block">
                {% if add_state %}
                <h2>Add state</h2>
                <form action="{% url 'add-chase-rule-state' rule.id %}" method="post">
                {% else %}
                <h2>Edit state</h2>
                <form action="{% url 'edit-chase-rule-state' state.id %}" method="post">
                {% endif %}
                {% csrf_token %}
                {{ form_state.as_p }}
                <input type="submit" value="Save" />
                </form>
                {% if add_cond %}
                <h2>Add condition</h2>
                <form action="{% url 'add-chase-rule-condition' rule.id %}" method="post">
                {% else %}
                <h2>Edit condition</h2>
                <form action="{% url 'edit-chase-rule-condition' condition.id %}" method="post">
                {% endif %}
                {% csrf_token %}
                {{ form_cond.as_p }}
                <input type="submit" value="Save" />
                </form>
            </div>
        </div>
{% endblock %}

soft/user_interface/config/templates/config/edit-config.html
{% extends "base.html" %}
{% load static %}
{% block title %}Edit a configuration{% endblock %}
{% block where_am_i %}
<li><a href="{% url 'edit-config' config.id %}">{{ config.name }}</a></li>
<li> > </li>
{% endblock %}
{% block content %}
        <div class="flex">
            <div class="block">
                <form action="{% url 'edit-config' config.id %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
            </form>
            </div>
            <div class="block">
                <h2>Continuous rules <a class="round-button" href="{% url 'add-continuous-rule' config.id %}">Add</a></h2>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Midi CC</th>
                        <th>Scale</th>
                        <th></th>
                    </tr>
                </thead>
                {% for rule in continuous_rules %}
                    <tr>
                        <td>{{ rule.name }}</td>
                        <td>#{{ rule.midi_cc }}</td>
                        <td>{{ rule.scale_down }} - {{ rule.scale_up }}</td>
                        <td class="last">
                            <a class="round-button" href="{% url 'edit-continuous-rule' rule.id %}">Edit</a>
                            <a class="round-button" href="{% url 'del-continuous-rule' rule.id %}">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            <h2>Standard rules <a class="round-button" href="{% url 'add-standard-rule' config.id %}">Add</a></h2>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Midi note</th>
                        <th>Event</th>
                        <th>Max duration</th>
                        <th></th>
                    </tr>
                </thead>
                {% for rule in standard_rules %}
                    <tr>
                        <td>{{ rule.name }}</td>
                        <td>#{{ rule.note }}</td>
                        <td>{{ rule.get_event_param_display }}</td>
                        <td>{{ rule.max_duration }}</td>
                        <td class="last">
                            <a class="round-button" href="{% url 'edit-standard-rule' rule.id %}">Edit</a>
                            <a class="round-button" href="{% url 'del-standard-rule' rule.id %}">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            <h2>Bank rules <a class="round-button" href="{% url 'add-bank-rule' config.id %}">Add</a></h2>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Max duration</th>
                        <th>States #note (priority)</th>
                        <th></th>
                    </tr>
                </thead>
                {% for rule in bank_rules %}
                    <tr>
                        <td>{{ rule.name }}</td>
                        <td>{{ rule.max_duration }}</td>
                        <td>{% for state in rule.bankrulestate_set.all %}
                            {{ state.name }} #{{ state.note }}  ({{ state.priority }}) <br />
                            {% endfor %}
                        </td>
                        <td class="last">
                            <a class="round-button" href="{% url 'edit-bank-rule' rule.id %}">Edit</a>
                            <a class="round-button" href="{% url 'del-bank-rule' rule.id %}">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            <h2>Chase rules <a class="round-button" href="{% url 'add-chase-rule' config.id %}">Add</a></h2>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Event</th>
                        <th>State duration</th>
                        <th>Random</th>
                        <th>States #note</th>
                        <th></th>
                    </tr>
                </thead>
                {% for rule in chase_rules %}
                    <tr>
                        <td>{{ rule.name }}</td>
                        <td>{{ rule.get_event_param_display }}</td>
                        <td>{{ rule.state_duration }}</td>
                        <td>{{ rule.random_states }}</td>
                         <td>{% for state in rule.chaserulestate_set.all %}
                            {{ state.name }} #{{ state.note }} <br />
                            {% endfor %}
                        </td>
                        <td class="last" >
                            <a class="round-button" href="{% url 'edit-chase-rule' rule.id %}">Editer</a>
                            <a class="round-button" href="{% url 'del-chase-rule' rule.id %}">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            </div>
        </div>
{% endblock %}

soft/user_interface/config/templates/config/edit-continuous-rule.html
{% extends "base.html" %}
{% load static %}
{% block title %}Edit a continuous rule{% endblock %}
{% block where_am_i %}
<li><a href="{% url 'edit-config' config.id %}">{{ config.name }}</a></li>
<li> > </li>
<li> Continuous rule </li>
<li> > </li>
{% if add %}
<li>New continuous rule</li>
{% else %}
<li><a href="{% url 'edit-continuous-rule' rule.id %}">{{ rule.name }}</a></li>
{% endif %}
{% endblock %}
{% block content %}
        <div class="flex">
            <div class="block">
                {% if add %}
                <form action="{% url 'add-continuous-rule' config.id %}" method="post">
                {% else %}
                <form action="{% url 'edit-continuous-rule' rule.id %}" method="post">
                {% endif %}
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
                </form>
            </div>
        </div>
{% endblock %}

soft/user_interface/config/templates/config/edit-standard-rule.html
{% extends "base.html" %}
{% load static %}
{% block title %}Edit a continuous rule{% endblock %}
{% block where_am_i %}
<li><a href="{% url 'edit-config' config.id %}">{{ config.name }}</a></li>
<li> > </li>
<li> Standard rule </li>
<li> > </li>
{% if add %}
<li>New standard rule</li>
{% else %}
<li><a href="{% url 'edit-standard-rule' rule.id %}">{{ rule.name }}</a></li>
{% endif %}
{% endblock %}
{% block content %}
        <div class="flex">
            <div class="block">
                {% if add %}
                <form action="{% url 'add-standard-rule' config.id %}" method="post">
                {% else %}
                <form action="{% url 'edit-standard-rule' rule.id %}" method="post">
                {% endif %}
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Save" />
                </form>
            </div>
            {% if not add %}
                <div class="block">
                    <h2>Conditions</h2>
                    <table>
                        <thead>
                            <tr>
                                <th>Conditions</th>
                                <th></th>
                            </tr>
                        </thead>
                        {% for cond in rule.standardrulecondition_set.all %}
                            <tr>
                                <td>{{ cond }} </td>
                                <td class="last">
                                    <a class="round-button" href="{% url 'edit-standard-rule-condition' cond.id %}">Edit</a>
                                    <a class="round-button" href="{% url 'del-standard-rule-condition' cond.id %}">Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
                <div class="block">
                    {% if add_cond %}
                    <h2>Add condition</h2>
                    <form action="{% url 'add-standard-rule-condition' rule.id %}" method="post">
                    {% else %}
                    <h2>Edit condition</h2>
                    <form action="{% url 'edit-standard-rule-condition' condition.id %}" method="post">
                    {% endif %}
                    {% csrf_token %}
                    {{ form_cond.as_p }}
                    <input type="submit" value="Save" />
                    </form>
                </div>
            {% endif %}
        </div>
{% endblock %}

soft/user_interface/config/templates/config/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Console{% endblock %}
{% block content %}
    <h1>Console</h1>
    <form action='#' id='consoleForm' method='get'>
        <textarea id="console" cols='120' rows='20' readonly="true" style="background-color:black;color:white;"></textarea>
    </form>

    <script type = 'application/javascript' src = 'https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js' ></script>
    <script type = 'application/javascript'>
    {% include "config/console.js" %}
    </script>
{% endblock %}

soft/user_interface/config/templates/config/list-config.html
{% extends "base.html" %}
{% load static %}
{% block title %}Configurations list{% endblock %}
{% block content %}
    <h1>Conifigurations list <a class="round-button" href="{% url 'add-config' %}">Add configuration</a></h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Creation</th>
                <th></th>
            </tr>
        </thead>
        {% for config in configs %}
            <tr {% if config.active %} id="active-row" {% endif %}>
                <td>{{ config.name }}</td>
                <td>{{ config.description }}</td>
                <td>{{ config.creation|date:"SHORT_DATETIME_FORMAT" }}</td>
                <td class="last">
                {% if not config.active %}
                <a class="round-button" href="{% url 'active-config' config.id %}">Active</a>
                {% endif %}
                <a class="round-button" href="{% url 'edit-config' config.id %}">Edit</a>
                <a class="round-button" href="{% url 'del-config' config.id %}">Delete</a></td>
            </tr>
        {% empty %}
            <p>No config</p>
        {% endfor %}
    </table>
{% endblock %}